"""Clean raw Superstore orders into data/clean/lines.parquet and log every check in DATA_QUALITY.md."""
import os

import duckdb

con = duckdb.connect()
# cp1252 encoding required for this Superstore CSV
con.execute("CREATE TABLE raw AS SELECT * FROM read_csv('data/raw/Sample - Superstore.csv', encoding='cp1252')")
one = lambda q: con.sql(q).fetchone()[0]

# (check, count, decision) -- every count comes from a query on the raw table
checks = [
    ("Raw order line rows", one("SELECT count(*) FROM raw"), "Starting point"),
    ("Duplicate Row ID", one("SELECT count(*) - count(DISTINCT \"Row ID\") FROM raw"), "Dropped"),
    ("Sales <= 0", one("SELECT count(*) FROM raw WHERE \"Sales\" <= 0"), "Dropped"),
    ("Quantity <= 0", one("SELECT count(*) FROM raw WHERE \"Quantity\" <= 0"), "Dropped"),
    ("Discount outside [0,1)", one("SELECT count(*) FROM raw WHERE \"Discount\" < 0 OR \"Discount\" >= 1"), "Dropped"),
    ("Ship Date < Order Date", one("SELECT count(*) FROM raw WHERE \"Ship Date\" < \"Order Date\""), "Dropped"),
    ("Exact duplicate lines (ignoring Row ID)", one("SELECT count(*) FROM (SELECT * FROM raw QUALIFY row_number() OVER (PARTITION BY \"Order ID\", \"Order Date\", \"Customer ID\", \"Product ID\", \"Quantity\", \"Sales\", \"Discount\" ORDER BY \"Row ID\") > 1)"), "Kept (legit repeat purchases)"),
    ("Null in key fields (Order ID, Order Date, Product ID, Sales, Quantity)", one("SELECT count(*) FROM raw WHERE \"Order ID\" IS NULL OR \"Order Date\" IS NULL OR \"Product ID\" IS NULL OR \"Sales\" IS NULL OR \"Quantity\" IS NULL"), "None found; would be dropped"),
    ("Negative profit lines", one("SELECT count(*) FROM raw WHERE \"Profit\" < 0"), "Kept (phenomenon under study)"),
    ("Distinct discount values count", one("SELECT count(DISTINCT \"Discount\") FROM raw"), "Distribution for discount_band"),
    ("Order date range (min, max)", f"{one('SELECT min(\"Order Date\") FROM raw')} to {one('SELECT max(\"Order Date\") FROM raw')}", "Temporal coverage"),
    ("Lines per year", "; ".join(f"{y}: {n:,}" for y, n in con.sql('SELECT year("Order Date"), count(*) FROM raw GROUP BY 1 ORDER BY 1').fetchall()), "Four full years; seasonality compared month-on-month"),
    ("Product IDs with multiple Product Names", one("SELECT count(*) FROM (SELECT \"Product ID\", count(DISTINCT \"Product Name\") as name_count FROM raw GROUP BY \"Product ID\" HAVING name_count > 1)"), "Known Superstore quirk; kept as-is"),
    ("States that never discount", one("SELECT count(DISTINCT \"State\") FROM raw WHERE \"State\" NOT IN (SELECT DISTINCT \"State\" FROM raw WHERE \"Discount\" > 0)"), "Possible region-set pricing policy"),
    ("Country (should be constant)", one("SELECT count(DISTINCT \"Country\") FROM raw"), "Dropped (single value: United States)"),
    ("Columns not needed: Customer Name, Postal Code, Row ID", 3, "Dropped: personal name not needed; analysis is at state/region level"),
]
con.execute(open("sql/00_clean.sql", encoding="utf-8").read())
kept = one("SELECT count(*) FROM lines")
checks.append(("Final clean lines", kept, "One row per order line"))
os.makedirs("data/clean", exist_ok=True)
con.execute("COPY lines TO 'data/clean/lines.parquet' (FORMAT parquet)")

with open("DATA_QUALITY.md", "w", encoding="utf-8") as f:
    f.write("# Data quality log\n\nGenerated by `clean.py`; every count comes from a query (the dropped-column count is the list itself).\n\n"
            "| Check | Result | Decision |\n|---|---|---|\n")
    f.writelines(f"| {c} | {n:,} | {d} |\n" if isinstance(n, int) else f"| {c} | {n} | {d} |\n" for c, n, d in checks)
dropped = checks[0][1] - kept
print(f"raw {checks[0][1]} = kept {kept} + dropped {dropped}")
